import bambo from '../../../public/brand/bambo.png'
import vietnamairline from '../../../public/brand/vietnamairline.png'

export const arrayFlight = [
    {
        id: 1,
        logo: bambo,
        name: 'Bamboo Airways',
        timeStart: '21:40',
        timeEnd: '23:10',
        timeTotal: '1h 30m',
        dayFlight: 'Fri, 22 Mar, 2022',
        dayLand: 'Fri, 22 Mar, 2022',
        transit: 'Direct',
        from: { name: 'Da Nang', code: 'DAD' },
        to: { name: 'Ho Chi Minh', code: 'SGN' },
        airportFrom: 'Da Nang Airport',
        airportTo: 'Tansonnhat Intl',
        baggage: '20kg',
        price: '1.500.000',
        priceSale: '1.200.000',
        isSale: true,
        isChoose: false,
        Aircraft: " Airbus A321",
        aircraftNumber: "VN-A588",
        typeClass: "Economy",
        typeFlight: "Round-trip",
    },
    {
        id: 2,
        logo: vietnamairline,
        name: 'Vietnam Airlines',
        timeStart: '21:40',
        timeEnd: '23:10',
        timeTotal: '1h 30m',
        dayFlight: 'Fri, 22 Mar, 2022',
        dayLand: 'Fri, 22 Mar, 2022',
        transit: 'Direct',
        from: { name: 'Da Nang', code: 'DAD' },
        to: { name: 'Ha Noi', code: 'HAN' },
        airportFrom: 'Da Nang Airport',
        airportTo: 'Noibai Intl',
        baggage: '20kg',
        price: '1.500.000',
        priceSale: '1.200.000',
        isSale: true,
        isChoose: false,
        Aircraft: " Airbus A321",
        aircraftNumber: "VN-A588",
        typeClass: "Economy",
        typeFlight: "Round-trip",
    },
    {
        id: 3,
        logo: bambo,
        name: 'Bamboo Airways',
        timeStart: '21:40',
        timeEnd: '23:10',
        timeTotal: '1h 30m',
        dayFlight: 'Fri, 22 Mar, 2022',
        dayLand: 'Fri, 22 Mar, 2022',
        transit: 'Direct',
        from: { name: 'Da Nang', code: 'DAD' },
        to: { name: 'Ho Chi Minh', code: 'SGN' },
        airportFrom: 'Da Nang Airport',
        airportTo: 'Tansonnhat Intl',
        baggage: '20kg',
        price: '1.500.000',
        priceSale: '1.200.000',
        isSale: true,
        isChoose: false,
        Aircraft: " Airbus A321",
        aircraftNumber: "VN-A588",
        typeClass: "Economy",
        typeFlight: "Round-trip",
    },
    {
        id: 4,
        logo: vietnamairline,
        name: 'Vietnam Airlines',
        timeStart: '21:40',
        timeEnd: '23:10',
        timeTotal: '1h 30m',
        dayFlight: 'Fri, 22 Mar, 2022',
        dayLand: 'Fri, 22 Mar, 2022',
        transit: 'Direct',
        from: { name: 'Da Nang', code: 'DAD' },
        to: { name: 'Ha Noi', code: 'HAN' },
        airportFrom: 'Da Nang Airport',
        airportTo: 'Noibai Intl',
        baggage: '20kg',
        price: '1.500.000',
        priceSale: '1.200.000',
        isSale: true,
        isChoose: false,
        Aircraft: " Airbus A321",
        aircraftNumber: "VN-A588",
        typeClass: "Economy",
        typeFlight: "Round-trip",
    },
    {
        id: 5,
        logo: bambo,
        name: 'Bamboo Airways',
        timeStart: '21:40',
        timeEnd: '23:10',
        timeTotal: '1h 30m',
        dayFlight: 'Fri, 22 Mar, 2022',
        dayLand: 'Fri, 22 Mar, 2022',
        transit: 'Direct',
        from: { name: 'Da Nang', code: 'DAD' },
        to: { name: 'Ho Chi Minh', code: 'SGN' },
        airportFrom: 'Da Nang Airport',
        airportTo: 'Tansonnhat Intl',
        baggage: '20kg',
        price: '1.500.000',
        priceSale: '1.200.000',
        isSale: true,
        isChoose: false,
        Aircraft: " Airbus A321",
        aircraftNumber: "VN-A588",
        typeClass: "Economy",
        typeFlight: "Round-trip",
    },
    {
        id: 6,
        logo: vietnamairline,
        name: 'Vietnam Airlines',
        timeStart: '21:40',
        timeEnd: '23:10',
        timeTotal: '1h 30m',
        dayFlight: 'Fri, 22 Mar, 2022',
        dayLand: 'Fri, 22 Mar, 2022',
        transit: 'Direct',
        from: { name: 'Da Nang', code: 'DAD' },
        to: { name: 'Ha Noi', code: 'HAN' },
        airportFrom: 'Da Nang Airport',
        airportTo: 'Noibai Intl',
        baggage: '20kg',
        price: '1.500.000',
        priceSale: '1.200.000',
        isSale: true,
        isChoose: false,
        Aircraft: " Airbus A321",
        aircraftNumber: "VN-A588",
        typeClass: "Economy",
        typeFlight: "Round-trip",
    },
    {
        id: 7,
        logo: vietnamairline,
        name: 'Vietnam Airlines',
        timeStart: '21:40',
        timeEnd: '23:10',
        timeTotal: '1h 30m',
        dayFlight: 'Fri, 22 Mar, 2022',
        dayLand: 'Fri, 22 Mar, 2022',
        transit: 'Direct',
        from: { name: 'Da Nang', code: 'DAD' },
        to: { name: 'Ha Noi', code: 'HAN' },
        airportFrom: 'Da Nang Airport',
        airportTo: 'Noibai Intl',
        baggage: '20kg',
        price: '1.500.000',
        priceSale: '1.200.000',
        isSale: true,
        isChoose: false,
        Aircraft: " Airbus A321",
        aircraftNumber: "VN-A588",
        typeClass: "Economy",
        typeFlight: "Round-trip",
    }
]